syntax enable
set nu
set tabstop=4
set expandtab
set cin
set autoindent
set smartindent
set shiftwidth=4
set cursorline

colorscheme molokai
execute pathogen#infect()
filetype plugin indent on
let g:go_disable_autoinstall = 0

let g:tagbar_type_go = {
    \ 'ctagstype' : 'go',
    \ 'kinds'     : [
        \ 'p:package',
        \ 'i:imports:1',
        \ 'c:constants',
        \ 'v:variables',
        \ 't:types',
        \ 'n:interfaces',
        \ 'w:fields',
        \ 'e:embedded',
        \ 'm:methods',
        \ 'r:constructor',
        \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 't' : 'ctype',
        \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
        \ 'ctype' : 't',
        \ 'ntype' : 'n'
    \ },
    \ 'ctagsbin'  : 'gotags',
    \ 'ctagsargs' : '-sort -silent'
\ }

let g:neocomplete#enable_at_startup = 1

nmap <F8> :TagbarToggle<CR>
map <C-n> :NERDTreeToggle<CR>
nmap ww <C-W><C-W>

